"""VoxFrontier (package: voxfrontier).

An open-source, fully reproducible pipeline for studying how live-streamer
voice characteristics relate to streaming efficiency:

1. DEA efficiency measurement (input-oriented BCC / CCR, three model specs).
2. Attribution: exact Shapley decomposition over input groups, random-forest
   importance, optional SHAP, Tobit (censored) regression, mediation analysis.
3. Non-linearity: quadratic (U-shape) tests, threshold (regime-switching)
   regression, quantile-band effects, subgroup interactions.
4. Causality: cross-fitted double machine learning with Neyman-orthogonal
   scores, FWL benchmarks, and efficiency-band heterogeneity.
5. Inference: bootstrap CIs, Hansen-style threshold tests, split-conformal
   prediction intervals, super-efficiency frontier ranking.
6. Counterfactual simulation: six intervention scenarios and per-unit
   diagnostics, with tamper-evident run manifests.

The public repository ships **only synthetic data** (generated by
``voxfrontier synth``); no real streamer, room, or platform data is included.
"""

from importlib.metadata import PackageNotFoundError, version

try:  # single source of truth: pyproject.toml
    __version__ = version("voxfrontier")
except PackageNotFoundError:  # editable / source tree without install
    __version__ = "0.0.0.dev0"

__all__ = ["__version__"]
